### ISSUE TITLE
Doesn't make

### ISSUE THREAD

**Issue by Kreijstal** [walterdejong/pconsole#5]
executing `make install`
gives
```
Makefile:49: .depend: No such file or directory
gcc -Iinclude -M List.c Conn.c cstring.c terminal.c commands.c pconsole.c > .depend
In file included from Conn.c:24:0:
include/Conn.h:26:20: fatal error: config.h: No such file or directory
compilation terminated.
In file included from cstring.c:24:0:
include/cstring.h:26:20: fatal error: config.h: No such file or directory
compilation terminated.
In file included from terminal.c:25:0:
include/cstring.h:26:20: fatal error: config.h: No such file or directory
compilation terminated.
In file included from commands.c:26:0:
include/cstring.h:26:20: fatal error: config.h: No such file or directory
compilation terminated.
In file included from pconsole.c:26:0:
include/cstring.h:26:20: fatal error: config.h: No such file or directory
compilation terminated.
Makefile:77: recipe for target '.depend' failed
make: *** [.depend] Error 1
```

**Comment by walterdejong** [comment]
Please try this:

```
$ ./configure

$ make dep

$ make
```

and see if that succeeds. Proceed with `make install` if it does.

**Comment by walterdejong** [comment]
It can't find config.h
Should be fixed in commit aacd5ee

**Comment by xtaran** [comment]
> It can't find config.h
> Should be fixed in commit aacd5ee

Doesn't fix it for me.

What fixed it for me was this patch:

```patch
--- a/include/Conn.h
+++ b/include/Conn.h
@@ -23,7 +23,7 @@
 #ifndef CONN_H_WJ101
 #define CONN_H_WJ101   1
 
-#include "config.h"
+#include "../config.h"
 #include "List.h"
 
 #ifdef HAVE_ST_RDEV
--- a/include/cstring.h
+++ b/include/cstring.h
@@ -23,7 +23,7 @@
 #ifndef CSTRING_H_WJ101
 #define CSTRING_H_WJ101        1
 
-#include "config.h"
+#include "../config.h"
 
 #include <string.h>
 
```
